
epochs: 1500
threshold: 0.35

optimization:
  lr: 0.0001
  lr_backbone: 0.0001
  optimizer:
    weight_decay: 0.0005
    clip_max_norm: 0.1
  scheduler:
    lr_step: 1200

loss:
  parameters:
    focal_alpha: 0.25
    set_cost_class: 2
    set_cost_point: 5
    set_cost_giou: 2
  coefficients:
    cls_coef: 2
    point_coef: 5
    giou_coef: 2

augmentation:
  num_crops: 1
  crop_size: 256
  min_scale: 0.7
  max_scale: 1.3
  gray_scale_prob: 0.1

model:
  backbone: "resnet50"
  channel_point: 3
  position_embedding: "sine"
  auxiliary_loss: true
  dilation: false
  transformer:
    encoder_layers: 6
    decoder_layers: 6
    dim_feedforward: 2048
    hidden_dim: 256
    dropout: 0.1
    num_heads: 8
    num_queries: 500
    pre_norm: false