
epochs: 1000
reduction: 8
regression: True
bins:
  - [0.0, 0.0]
  - [1.0, 1.0]
  - [2.0, .inf]
anchor_points:
  - 0.0
  - 1.0
  - 2.10737

optimization:
  lr: 0.0001
  optimizer:
    weight_decay: 0.0001
  scheduler:
    warmup_lr: 0.000001
    warmup_epochs: 50
    T_0: 5
    T_mult: 2
    eta_min: 0.0000001

loss:
  weights:
    weight_ot: 0.1
    weight_tv: 0.01
    weight_count_loss: 1.0
    regularization: 10.0
  parameters:
    num_iter_in_ot: 100
    norm_cood: 0
    count_loss_type: "dmcount"

augmentation:
  num_crops: 1
  min_scale: 1.0
  max_scale: 2.0
  kernel_size: 5
  color_jitter:
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0.0
  noise:
    saltiness: 0.001
    spiciness: 0.001
  probabilities:
    jitter_prob: 0.2
    blur_prob: 0.2
    noise_prob: 0.5

model:
  backbone: "vgg16_bn"