
epochs: 600

optimization:
  lr: 0.00001
  optimizer:
    optimizer_type: "adamW"
    betas: [ 0.9, 0.999 ]
    weight_decay: 0.01
    eps: 0.00000001
    momentum: 0.9
    amsgrad: false
    nesterov: true
  scheduler:
    scheduler_type: "cosine"
    warmup_lr: 0.0000005
    warmup_epochs: 10
    decay_epochs: 250
    decay_rate: 0.1
    min_lr: 0.0000001

loss:
  baseline_loss: false
  loss_weight: [ 1.0, 0.5, 0.25, 0.125 ]
  density_factor: 100

augmentation:
  crop_size: 768
  num_crops: 1
  route_size: 256
  shuffle: true
  flip: true
  multi_scale: true
  scale_factor: [ 0.5, 2.0 ]
  downsamplerate: 1
  ignore_label: 255

model:
  feature_extraction:
    backbone: "hrnet_w48" # vit_base, vit_large, vit_huge, vgg16_bn, vgg16, vgg19_bn, vgg19, hrnet_w32, hrnet_w48, hrnet_w64
    backbone_type: "MocHRBackbone"
    counter_type: "withMOE"  # 'withMOE' or 'baseline'
    resolution_num: [ 0,1,2,3 ]
    sigma: [ 4 ]
    gau_kernel_size: 11
    pretrained: true

  head_counting:
    head_type: "CountingHead"
    fuse_method: "cat"
    in_channels: 96
    stages_channel: [ 384, 192, 96, 48 ]
    inter_layer: [ 64, 32, 16 ]
    out_channels: 1
